LOCAL_PATH:= $(call my-dir)

include $(CLEAR_VARS)
LOCAL_MODULE_TAGS := optional

LOCAL_MODULE := DigitalWellbeing
LOCAL_MODULE_CLASS := APPS
LOCAL_CERTIFICATE := PRESIGNED

LOCAL_SRC_FILES :=DigitalWellbeing.apk

LOCAL_MODULE_PATH := $(TARGET_OUT)/priv-app

include $(BUILD_PREBUILT)
