/* generated by mediatek */

package com.cydroid.featureoption;

public final class FeatureOption
{
    /**
     * check if GN_APK_HAS_JNI_LIBRARIES is turned on or not
     */
    public static final boolean GN_APK_HAS_JNI_LIBRARIES = true;
}
